.TH SECRET 1
.SH NAME
secret \- send encrypted files via ICMP
.SH SYNOPSIS
.B secret
[\fB\-h\fR]
[\fB\-s\fR \fINAME\fR]
[\fB\-r\fR \fIFILE\fR]
[\fB\-l\fR]
.IR file ...
.SH DESCRIPTION
.B secret
send encrypted files via ICMP.
AES with hardcoded 128b key is used for encryption.
To enter sending mode both \fB\-s\fR and \fB\-r\fR parameters must be specified.
.SH OPTIONS
.TP
.BR \-h
Print help message and exit.
.TP
.BR \-s " \fINAME\fR "
speciy receiver address or hostname.
.TP
.BR \-r " \fIFILE
specify FILE to send.
.TP
.BR \-l
enter listen mode, saving received files in current directory.